// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Tea_app = require("bucklescript-tea/src-ocaml/tea_app.bs.js");
var Tea_html = require("bucklescript-tea/src-ocaml/tea_html.bs.js");

function set(param_0) {
  return /* Set */{
          _0: param_0
        };
}

function init(param) {
  return 4;
}

function update(model, v) {
  if (typeof v !== "number") {
    return v._0;
  }
  switch (v) {
    case /* Increment */0 :
        return model + 1 | 0;
    case /* Decrement */1 :
        return model - 1 | 0;
    case /* Reset */2 :
        return 0;
    
  }
}

function view_button(title, msg) {
  return Tea_html.button(undefined, undefined, {
              hd: Tea_html.onClick(msg),
              tl: /* [] */0
            }, {
              hd: Tea_html.text(title),
              tl: /* [] */0
            });
}

function view(model) {
  return Tea_html.div(undefined, undefined, /* [] */0, {
              hd: Tea_html.span(undefined, undefined, {
                    hd: Tea_html.style("text-weight", "bold"),
                    tl: /* [] */0
                  }, {
                    hd: Tea_html.text(String(model)),
                    tl: /* [] */0
                  }),
              tl: {
                hd: Tea_html.br(/* [] */0),
                tl: {
                  hd: view_button("Increment", /* Increment */0),
                  tl: {
                    hd: Tea_html.br(/* [] */0),
                    tl: {
                      hd: view_button("Decrement", /* Decrement */1),
                      tl: {
                        hd: Tea_html.br(/* [] */0),
                        tl: {
                          hd: view_button("Set to 42", /* Set */{
                                _0: 42
                              }),
                          tl: {
                            hd: Tea_html.br(/* [] */0),
                            tl: {
                              hd: model !== 0 ? view_button("Reset", /* Reset */2) : Tea_html.noNode,
                              tl: /* [] */0
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            });
}

function main(param) {
  console.log("Hello, from Main!");
  var partial_arg = {
    model: 4,
    update: update,
    view: view
  };
  return function (param, param$1) {
    return Tea_app.beginnerProgram(partial_arg, param, param$1);
  };
}

main(undefined);

var increment = /* Increment */0;

var decrement = /* Decrement */1;

var reset = /* Reset */2;

exports.increment = increment;
exports.decrement = decrement;
exports.reset = reset;
exports.set = set;
exports.init = init;
exports.update = update;
exports.view_button = view_button;
exports.view = view;
exports.main = main;
/*  Not a pure module */
